services:

  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    container_name: nextjs
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - crypto-vault

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
      - postgresql
    networks:
      - crypto-vault

  postgresql:
    image: postgres:14
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - crypto-vault

networks:
  crypto-vault: ~
