services:

  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    container_name: nextjs
    networks:
      - crypto-vault

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - crypto-vault

networks:
  crypto-vault: ~
